### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by GReaperEx** [allender/emulator#6]
Because g++ added a bunch of warnings that have to do with memory access and indentation, the rep currently fails to build. I worked around that by removing the "-Werror" from CMakeLists.txt

Also, the final phase of the build fails before it doesn't find the "disks" folder. No big problem, I just created it manually, but it should either be created automatically or removed altogether.

Oh, you should also add in the README that GTK+3.0 is required.

**Comment by allender** [comment]
Thanks for reporting.  I will get these fixed up.

**Comment by allender** [comment]
hello - I have pushed updated code (along with some bug fixes and new updated libraries.  Compilation looks clean again on all platforms.  README updated, and all folders are now created by cmake.  Let me know if you have more issues.  Thanks for your interest.
